### ISSUE TITLE
PowerShell DSC module cDisk missing

### ISSUE THREAD

**Issue by achimismaili** [NikCharlebois/Conferences#2]
Hello Nik, thanks for this great solution.
I was experiencing the following issue, when I was trying to reproduce the installation of the farm via Azure DevOps from the folder "2019 - Collaboration Summit Europe":

File: SharePoint2019.ps1, Line 12:
Import-DscResource -ModuleName "cDisk"               -ModuleVersion "1.0"

This module seems not to be available anymore and I did not find it anywhere.

(https://github.com/NikCharlebois/Conferences/blob/master/2019%20-%20CollabSummit%20-%20Europe/DSC/SharePoint2019.ps1)

**Comment by achimismaili** [comment]
How about instead using:

Import-DscResource -ModuleName "StorageDsc"           -ModuleVersion "4.7.0.0"

... and replace cDisk configuration with:

    Disk SPDataDisk
        {
            DiskId               = 2
            DriveLetter          = "F"
            DependsOn            = "[xWaitforDisk]Disk2"
            PsDscRunAsCredential = $Admincreds
            FSFormat             = "NTFS"
        }

**Comment by NikCharlebois** [comment]
Thanks, cDisk is actually a custom module we had been using in the Azure Quick Start Examples, and can be found at:
https://github.com/Azure/azure-quickstart-templates/blob/master/sharepoint-three-vm/dsc/PrepareSharePointServer.ps1.zip

I unfortunately won't have time anytime soon to make the change here and test....unless you want to submit a PR yourself (wink wink) 😄

**Comment by achimismaili** [comment]
Thank you very much, Nik. That should solve it.
Regarding PR, will see ... ;)
